# Generated by Django 5.1.3 on 2024-11-24 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_customer_is_active_customer_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
