# Generated by Django 5.1.3 on 2024-12-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_customer_password_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
    ]
