# Generated by Django 5.1.3 on 2024-11-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customuser',
        ),
    ]
